rp:
  environment:
    variable:
      clean:
        storage:
          cron: '*/10 * * * * *'
          chunkSize: 1000
        attachment:
          cron: '*/30 * * * * *'
      storage:
        project:
            cron: '*/30 * * * * *'
      executor:
        pool:
          storage:
            project:
              core: 5
              max: 10

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: ${rp.db.url}
    username: ${rp.db.user}
    password: ${rp.db.pass}
    maximumPoolSize: 27

  db:
    url: jdbc:postgresql://${rp.db.host}:${rp.db.port}/${rp.db.name}
    name: reportportal
    host: localhost
    port: 5432
    user: rpuser
    pass: rppass

datastore:
  path: /data/storage
  minio:
    endpoint: http://localhost:9000
    accessKey: minio
    secretKey: minio123
    bucketPrefix: prj-
    defaultBucketName: rp-bucket
    region: #{null}
  # could be one of [filesystem, minio]
  type: minio


